### ISSUE TITLE
timed autosave (feature request)

### ISSUE THREAD

**Issue by juhacarlon** [LaughingLeader-DOS2-Mods/LeaderLib#3]
i think we can agree that the autosaving in this game is terrible, i read online that this mod has a feaure that betters this, is that true? and if not, is there a possibility that it could be added , or made as a standalone mod.
im a coder too, and a fan.
thanks for making this

**Comment by LaughingLeader** [comment]
Yes, timed autosaving is a feature. It's actually [one of the two screenshots on the mod page](https://steamuserimages-a.akamaihd.net/ugc/960850363679922740/70D4474CF30396A4DCAE7D72DAC2D94792CF380E/).
